//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player Controller"",
            ""id"": ""75993231-eb43-4c48-bf47-ca3fc5751609"",
            ""actions"": [
                {
                    ""name"": ""LMB"",
                    ""type"": ""Button"",
                    ""id"": ""efb964f3-ebc1-4498-ac20-c3ebb34388f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RMD"",
                    ""type"": ""Button"",
                    ""id"": ""e911fde2-895a-44ff-be22-5f284ef16d12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MMB"",
                    ""type"": ""Button"",
                    ""id"": ""98fe302a-5d77-42f2-834c-94fc4c5cb2fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""ba1d82be-807a-4780-9b62-a3b6618cd039"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shift"",
                    ""type"": ""Button"",
                    ""id"": ""b147900a-4b45-4c3b-9351-7c665ab560f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alt"",
                    ""type"": ""Button"",
                    ""id"": ""fed4d913-bff9-4ad1-aa56-4091ab5c3fad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""b1bee71b-d2f7-4c1b-ab57-82ccbccc546a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""d34d66d0-f4c3-438c-a336-9b525cbf04d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""b1372a3f-3209-4d2f-b628-a9dd65404d4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E"",
                    ""type"": ""Button"",
                    ""id"": ""ac9900b1-4e08-4813-958f-00104133db7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Q"",
                    ""type"": ""Button"",
                    ""id"": ""a3ea28b8-5a28-4677-bbc9-26fdd590da3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R"",
                    ""type"": ""Button"",
                    ""id"": ""b0462179-224b-4e95-9e2b-a6636dffc470"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F"",
                    ""type"": ""Button"",
                    ""id"": ""3c280ef9-b7ac-47c2-94f2-a482d446022d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM1"",
                    ""type"": ""Button"",
                    ""id"": ""7e5ecece-67c9-4d2d-bd41-5cb699860bb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM2"",
                    ""type"": ""Button"",
                    ""id"": ""08620758-6d4c-46d7-9286-771139a163a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM3"",
                    ""type"": ""Button"",
                    ""id"": ""91f311ff-a403-4471-be1f-cb2bb1b1fe14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM4"",
                    ""type"": ""Button"",
                    ""id"": ""2e9ccd4b-bef1-4c19-9d08-c14cea9b72f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM5"",
                    ""type"": ""Button"",
                    ""id"": ""a77f014a-0312-4e21-bc32-6ad62ab0ec1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM6"",
                    ""type"": ""Button"",
                    ""id"": ""3a47f562-a6aa-4ca4-ae43-c1b505538416"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM7"",
                    ""type"": ""Button"",
                    ""id"": ""00ac702f-68d4-4b6a-9ef2-a2f7efd2e9cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM8"",
                    ""type"": ""Button"",
                    ""id"": ""dcf1c45b-91bb-4de6-9b50-f76be8f32764"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM9"",
                    ""type"": ""Button"",
                    ""id"": ""ee70a434-7054-4152-a8be-67bd39843119"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NUM0"",
                    ""type"": ""Button"",
                    ""id"": ""3f0a8c37-1f76-4774-bf02-4edcf626c6c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""21899f12-100f-4955-816f-1cb9e019d1c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""297bb83d-23c9-4e97-8b3e-256d40f9a5ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""beb2e311-0c7a-45e8-961b-b7f1b989eba5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""3e5abf09-b357-48e6-8fe3-e9715fba3e45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""291aa978-2f9f-471f-a998-85d66dcafa19"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LMB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7edcf7e-1a93-49e5-9e0a-6e15ae24d060"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RMD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3582707-40b2-47c0-800b-3aabbc3982a9"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MMB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2efd7a3-9801-423f-8045-788719b8bc85"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cddfa5c9-d0db-4457-b8e8-8f3f593ddaac"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab187727-4df5-4b7d-818c-8fe62b5af6ca"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11404fb8-d311-4446-8bf8-6320bb94e92c"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3862a8e4-caf0-499c-b92c-9660dcabecfc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c93a569-adee-4d67-8923-b14e7eec46ab"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da0ab1ca-be04-4d61-b9bd-13b8c0bd8ad5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef9e8859-64b1-45df-b8d0-c3c8b95071bc"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""058b04d3-2f89-4413-86a0-67b6b23303be"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fc63927-8638-413b-b94b-cf6671033f20"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0ad050d-a39d-4f4c-8598-a9f7c7aed7e3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72fdd0f5-d937-4d5a-9c8a-16d292cbe5af"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24b96a6b-f25c-4669-a98d-f1c61674ee59"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aec68403-4147-45a1-8b6c-a951860e6c1d"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb14fc9c-f64e-4e6d-a3f4-60a67cb99035"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e92a892-6082-4be7-9314-9c409acf972c"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4d47d6e-4819-4fe4-b9e6-e78f839aeca4"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fab9b483-9efa-4d7f-976e-bf76d220f469"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b5b5bcd-20b0-4a36-a3aa-f771eb2fb8cf"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50784b99-02e3-48af-9e15-9921f6e81cd8"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NUM0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e556c2ae-519e-46ae-84f0-dce64d83bbc3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85723cc6-71b7-48ab-b696-102fa8e806cf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c38e65f-ffee-46db-9ee9-0b91f7fa7263"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89b18019-a33f-4a87-ae57-6d0c66375d30"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab926c0a-2030-4738-9327-c5f53a89496d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78677cbe-c94e-454e-9fe1-7e8c3bf888ea"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d064d930-3bf6-4117-a6bc-bf461866b28e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8470fac3-619c-4a4e-8db3-28b1b5a5444d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player Controller
        m_PlayerController = asset.FindActionMap("Player Controller", throwIfNotFound: true);
        m_PlayerController_LMB = m_PlayerController.FindAction("LMB", throwIfNotFound: true);
        m_PlayerController_RMD = m_PlayerController.FindAction("RMD", throwIfNotFound: true);
        m_PlayerController_MMB = m_PlayerController.FindAction("MMB", throwIfNotFound: true);
        m_PlayerController_Space = m_PlayerController.FindAction("Space", throwIfNotFound: true);
        m_PlayerController_Shift = m_PlayerController.FindAction("Shift", throwIfNotFound: true);
        m_PlayerController_Alt = m_PlayerController.FindAction("Alt", throwIfNotFound: true);
        m_PlayerController_Enter = m_PlayerController.FindAction("Enter", throwIfNotFound: true);
        m_PlayerController_Escape = m_PlayerController.FindAction("Escape", throwIfNotFound: true);
        m_PlayerController_Tab = m_PlayerController.FindAction("Tab", throwIfNotFound: true);
        m_PlayerController_E = m_PlayerController.FindAction("E", throwIfNotFound: true);
        m_PlayerController_Q = m_PlayerController.FindAction("Q", throwIfNotFound: true);
        m_PlayerController_R = m_PlayerController.FindAction("R", throwIfNotFound: true);
        m_PlayerController_F = m_PlayerController.FindAction("F", throwIfNotFound: true);
        m_PlayerController_NUM1 = m_PlayerController.FindAction("NUM1", throwIfNotFound: true);
        m_PlayerController_NUM2 = m_PlayerController.FindAction("NUM2", throwIfNotFound: true);
        m_PlayerController_NUM3 = m_PlayerController.FindAction("NUM3", throwIfNotFound: true);
        m_PlayerController_NUM4 = m_PlayerController.FindAction("NUM4", throwIfNotFound: true);
        m_PlayerController_NUM5 = m_PlayerController.FindAction("NUM5", throwIfNotFound: true);
        m_PlayerController_NUM6 = m_PlayerController.FindAction("NUM6", throwIfNotFound: true);
        m_PlayerController_NUM7 = m_PlayerController.FindAction("NUM7", throwIfNotFound: true);
        m_PlayerController_NUM8 = m_PlayerController.FindAction("NUM8", throwIfNotFound: true);
        m_PlayerController_NUM9 = m_PlayerController.FindAction("NUM9", throwIfNotFound: true);
        m_PlayerController_NUM0 = m_PlayerController.FindAction("NUM0", throwIfNotFound: true);
        m_PlayerController_Up = m_PlayerController.FindAction("Up", throwIfNotFound: true);
        m_PlayerController_Down = m_PlayerController.FindAction("Down", throwIfNotFound: true);
        m_PlayerController_Left = m_PlayerController.FindAction("Left", throwIfNotFound: true);
        m_PlayerController_Right = m_PlayerController.FindAction("Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player Controller
    private readonly InputActionMap m_PlayerController;
    private IPlayerControllerActions m_PlayerControllerActionsCallbackInterface;
    private readonly InputAction m_PlayerController_LMB;
    private readonly InputAction m_PlayerController_RMD;
    private readonly InputAction m_PlayerController_MMB;
    private readonly InputAction m_PlayerController_Space;
    private readonly InputAction m_PlayerController_Shift;
    private readonly InputAction m_PlayerController_Alt;
    private readonly InputAction m_PlayerController_Enter;
    private readonly InputAction m_PlayerController_Escape;
    private readonly InputAction m_PlayerController_Tab;
    private readonly InputAction m_PlayerController_E;
    private readonly InputAction m_PlayerController_Q;
    private readonly InputAction m_PlayerController_R;
    private readonly InputAction m_PlayerController_F;
    private readonly InputAction m_PlayerController_NUM1;
    private readonly InputAction m_PlayerController_NUM2;
    private readonly InputAction m_PlayerController_NUM3;
    private readonly InputAction m_PlayerController_NUM4;
    private readonly InputAction m_PlayerController_NUM5;
    private readonly InputAction m_PlayerController_NUM6;
    private readonly InputAction m_PlayerController_NUM7;
    private readonly InputAction m_PlayerController_NUM8;
    private readonly InputAction m_PlayerController_NUM9;
    private readonly InputAction m_PlayerController_NUM0;
    private readonly InputAction m_PlayerController_Up;
    private readonly InputAction m_PlayerController_Down;
    private readonly InputAction m_PlayerController_Left;
    private readonly InputAction m_PlayerController_Right;
    public struct PlayerControllerActions
    {
        private @InputActions m_Wrapper;
        public PlayerControllerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LMB => m_Wrapper.m_PlayerController_LMB;
        public InputAction @RMD => m_Wrapper.m_PlayerController_RMD;
        public InputAction @MMB => m_Wrapper.m_PlayerController_MMB;
        public InputAction @Space => m_Wrapper.m_PlayerController_Space;
        public InputAction @Shift => m_Wrapper.m_PlayerController_Shift;
        public InputAction @Alt => m_Wrapper.m_PlayerController_Alt;
        public InputAction @Enter => m_Wrapper.m_PlayerController_Enter;
        public InputAction @Escape => m_Wrapper.m_PlayerController_Escape;
        public InputAction @Tab => m_Wrapper.m_PlayerController_Tab;
        public InputAction @E => m_Wrapper.m_PlayerController_E;
        public InputAction @Q => m_Wrapper.m_PlayerController_Q;
        public InputAction @R => m_Wrapper.m_PlayerController_R;
        public InputAction @F => m_Wrapper.m_PlayerController_F;
        public InputAction @NUM1 => m_Wrapper.m_PlayerController_NUM1;
        public InputAction @NUM2 => m_Wrapper.m_PlayerController_NUM2;
        public InputAction @NUM3 => m_Wrapper.m_PlayerController_NUM3;
        public InputAction @NUM4 => m_Wrapper.m_PlayerController_NUM4;
        public InputAction @NUM5 => m_Wrapper.m_PlayerController_NUM5;
        public InputAction @NUM6 => m_Wrapper.m_PlayerController_NUM6;
        public InputAction @NUM7 => m_Wrapper.m_PlayerController_NUM7;
        public InputAction @NUM8 => m_Wrapper.m_PlayerController_NUM8;
        public InputAction @NUM9 => m_Wrapper.m_PlayerController_NUM9;
        public InputAction @NUM0 => m_Wrapper.m_PlayerController_NUM0;
        public InputAction @Up => m_Wrapper.m_PlayerController_Up;
        public InputAction @Down => m_Wrapper.m_PlayerController_Down;
        public InputAction @Left => m_Wrapper.m_PlayerController_Left;
        public InputAction @Right => m_Wrapper.m_PlayerController_Right;
        public InputActionMap Get() { return m_Wrapper.m_PlayerController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControllerActions instance)
        {
            if (m_Wrapper.m_PlayerControllerActionsCallbackInterface != null)
            {
                @LMB.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLMB;
                @LMB.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLMB;
                @LMB.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLMB;
                @RMD.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRMD;
                @RMD.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRMD;
                @RMD.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRMD;
                @MMB.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnMMB;
                @MMB.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnMMB;
                @MMB.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnMMB;
                @Space.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSpace;
                @Space.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSpace;
                @Space.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSpace;
                @Shift.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnShift;
                @Shift.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnShift;
                @Shift.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnShift;
                @Alt.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAlt;
                @Alt.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAlt;
                @Alt.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAlt;
                @Enter.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnEnter;
                @Escape.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnEscape;
                @Tab.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnTab;
                @Tab.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnTab;
                @Tab.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnTab;
                @E.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnE;
                @E.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnE;
                @E.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnE;
                @Q.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnQ;
                @Q.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnQ;
                @Q.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnQ;
                @R.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnR;
                @R.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnR;
                @R.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnR;
                @F.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnF;
                @F.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnF;
                @F.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnF;
                @NUM1.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM1;
                @NUM1.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM1;
                @NUM1.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM1;
                @NUM2.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM2;
                @NUM2.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM2;
                @NUM2.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM2;
                @NUM3.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM3;
                @NUM3.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM3;
                @NUM3.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM3;
                @NUM4.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM4;
                @NUM4.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM4;
                @NUM4.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM4;
                @NUM5.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM5;
                @NUM5.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM5;
                @NUM5.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM5;
                @NUM6.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM6;
                @NUM6.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM6;
                @NUM6.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM6;
                @NUM7.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM7;
                @NUM7.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM7;
                @NUM7.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM7;
                @NUM8.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM8;
                @NUM8.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM8;
                @NUM8.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM8;
                @NUM9.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM9;
                @NUM9.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM9;
                @NUM9.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM9;
                @NUM0.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM0;
                @NUM0.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM0;
                @NUM0.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnNUM0;
                @Up.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnUp;
                @Down.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnDown;
                @Down.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnDown;
                @Down.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnDown;
                @Left.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLeft;
                @Left.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLeft;
                @Left.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLeft;
                @Right.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRight;
                @Right.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRight;
                @Right.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRight;
            }
            m_Wrapper.m_PlayerControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LMB.started += instance.OnLMB;
                @LMB.performed += instance.OnLMB;
                @LMB.canceled += instance.OnLMB;
                @RMD.started += instance.OnRMD;
                @RMD.performed += instance.OnRMD;
                @RMD.canceled += instance.OnRMD;
                @MMB.started += instance.OnMMB;
                @MMB.performed += instance.OnMMB;
                @MMB.canceled += instance.OnMMB;
                @Space.started += instance.OnSpace;
                @Space.performed += instance.OnSpace;
                @Space.canceled += instance.OnSpace;
                @Shift.started += instance.OnShift;
                @Shift.performed += instance.OnShift;
                @Shift.canceled += instance.OnShift;
                @Alt.started += instance.OnAlt;
                @Alt.performed += instance.OnAlt;
                @Alt.canceled += instance.OnAlt;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
                @Tab.started += instance.OnTab;
                @Tab.performed += instance.OnTab;
                @Tab.canceled += instance.OnTab;
                @E.started += instance.OnE;
                @E.performed += instance.OnE;
                @E.canceled += instance.OnE;
                @Q.started += instance.OnQ;
                @Q.performed += instance.OnQ;
                @Q.canceled += instance.OnQ;
                @R.started += instance.OnR;
                @R.performed += instance.OnR;
                @R.canceled += instance.OnR;
                @F.started += instance.OnF;
                @F.performed += instance.OnF;
                @F.canceled += instance.OnF;
                @NUM1.started += instance.OnNUM1;
                @NUM1.performed += instance.OnNUM1;
                @NUM1.canceled += instance.OnNUM1;
                @NUM2.started += instance.OnNUM2;
                @NUM2.performed += instance.OnNUM2;
                @NUM2.canceled += instance.OnNUM2;
                @NUM3.started += instance.OnNUM3;
                @NUM3.performed += instance.OnNUM3;
                @NUM3.canceled += instance.OnNUM3;
                @NUM4.started += instance.OnNUM4;
                @NUM4.performed += instance.OnNUM4;
                @NUM4.canceled += instance.OnNUM4;
                @NUM5.started += instance.OnNUM5;
                @NUM5.performed += instance.OnNUM5;
                @NUM5.canceled += instance.OnNUM5;
                @NUM6.started += instance.OnNUM6;
                @NUM6.performed += instance.OnNUM6;
                @NUM6.canceled += instance.OnNUM6;
                @NUM7.started += instance.OnNUM7;
                @NUM7.performed += instance.OnNUM7;
                @NUM7.canceled += instance.OnNUM7;
                @NUM8.started += instance.OnNUM8;
                @NUM8.performed += instance.OnNUM8;
                @NUM8.canceled += instance.OnNUM8;
                @NUM9.started += instance.OnNUM9;
                @NUM9.performed += instance.OnNUM9;
                @NUM9.canceled += instance.OnNUM9;
                @NUM0.started += instance.OnNUM0;
                @NUM0.performed += instance.OnNUM0;
                @NUM0.canceled += instance.OnNUM0;
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
                @Down.started += instance.OnDown;
                @Down.performed += instance.OnDown;
                @Down.canceled += instance.OnDown;
                @Left.started += instance.OnLeft;
                @Left.performed += instance.OnLeft;
                @Left.canceled += instance.OnLeft;
                @Right.started += instance.OnRight;
                @Right.performed += instance.OnRight;
                @Right.canceled += instance.OnRight;
            }
        }
    }
    public PlayerControllerActions @PlayerController => new PlayerControllerActions(this);
    public interface IPlayerControllerActions
    {
        void OnLMB(InputAction.CallbackContext context);
        void OnRMD(InputAction.CallbackContext context);
        void OnMMB(InputAction.CallbackContext context);
        void OnSpace(InputAction.CallbackContext context);
        void OnShift(InputAction.CallbackContext context);
        void OnAlt(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnTab(InputAction.CallbackContext context);
        void OnE(InputAction.CallbackContext context);
        void OnQ(InputAction.CallbackContext context);
        void OnR(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnNUM1(InputAction.CallbackContext context);
        void OnNUM2(InputAction.CallbackContext context);
        void OnNUM3(InputAction.CallbackContext context);
        void OnNUM4(InputAction.CallbackContext context);
        void OnNUM5(InputAction.CallbackContext context);
        void OnNUM6(InputAction.CallbackContext context);
        void OnNUM7(InputAction.CallbackContext context);
        void OnNUM8(InputAction.CallbackContext context);
        void OnNUM9(InputAction.CallbackContext context);
        void OnNUM0(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
    }
}
